name: Daily Commit

on:
  schedule:
    - cron: '25 13 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
        
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        
      - name: Pull latest changes and handle conflicts
        run: |
          git fetch origin
          git rebase origin/${{ github.ref_name }} || {
            echo "Rebase failed, trying merge strategy"
            git rebase --abort
            git merge origin/${{ github.ref_name }} || {
              echo "Merge failed, forcing sync"
              git reset --hard origin/${{ github.ref_name }}
            }
          }
        
      - name: Create daily commit
        run: |
          echo "Daily commit on $(date)" >> daily_commit.txt
          git add daily_commit.txt
          
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Daily commit - $(date '+%Y-%m-%d %H:%M')"
            echo "Changes committed successfully"
          else
            echo "No changes to commit"
            exit 0
          fi
        
      - name: Push changes with retry
        run: |
          max_retries=3
          retry_count=0
          
          while [ $retry_count -lt $max_retries ]; do
            if git push origin ${{ github.ref_name }}; then
              echo "Push successful"
              exit 0
            else
              echo "Push failed, attempt $((retry_count + 1)) of $max_retries"
              retry_count=$((retry_count + 1))
              
              if [ $retry_count -lt $max_retries ]; then
                echo "Pulling latest changes and retrying..."
                git pull origin ${{ github.ref_name }} --rebase
                sleep 2
              fi
            fi
          done
          
          echo "Push failed after $max_retries attempts"
          exit 1
