name: Daily Commit

on:
  schedule:
    - cron: '25 13 * * *'  # Fixed: Added missing space - should be '* * *' not '**'
  
  # Allow the workflow to be manually triggered through the GitHub UI
  workflow_dispatch:

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch full history
        
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        
      - name: Create daily commit
        run: |
          echo "Daily commit on $(date)" >> daily_commit.txt
          git add daily_commit.txt
          git diff --staged --quiet || git commit -m "Daily commit - $(date '+%Y-%m-%d %H:%M')"
        
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin ${{ github.ref_name }}
