name: Daily Commit

on:
  schedule:
    - cron: '25 13 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        
      - name: Create daily commit
        run: |
          echo "Daily commit on $(date)" >> daily_commit.txt
          git add daily_commit.txt
          git commit -m "Daily commit - $(date '+%Y-%m-%d %H:%M')"
        
      - name: Force push changes
        run: |
          git push origin main --force
